export enum logs {
  contextMenuNotFoundButtonRef = 'ZOOMRC/CONTEXT_MENU/NOT_FOUND_BUTTON_REF',

  dialogNotFoundDialogRef = 'ZOOMRC/DIALOG/NOT_FOUND_DIALOG_REF',

  inputNotFoundInputRef = 'ZOOMRC/INPUT/NOT_FOUND_INPUT_REF',
  inputNotFoundLabelRef = 'ZOOMRC/INPUT/NOT_FOUND_LABEL_REF',

  selectNotFoundOptionsListRef = 'ZOOMRC/SELECT/NOT_FOUND_OPTIONS_LIST_REF',
  selectNotFoundContainerRef = 'ZOOMRC/SELECT/NOT_FOUND_CONTAINER_REF',
  selectNotFoundInputRef = 'ZOOMRC/SELECT/NOT_FOUND_INPUT_REF',

  textareaNotFoundTextareaRef = 'ZOOMRC/TEXTAREA/NOT_FOUND_TEXTAREA_REF',
  textareaNotFoundLabelRef = 'ZOOMRC/TEXTAREA/NOTFOUND_LABEL_REF',

  popoverNotFoundContainerRef = 'ZOOMRC/POPOVER/NOT_FOUND_CONTAINER_REF',

  couldNotCopyToClipboard = 'ZOOMRC/COPY_TO_CLIPBOARD/COULD_NOT_COPY_TO_CLIPBOARD',

  imageNotLoaded = 'ZOOMRC/IMAG_LOADER/COULD_NOT_LOAD_IMAGE',

  mentionNotFoundTextareaRef = 'ZOOMRC/MENTION/NOT_FOUND_TEXTAREA_REF',

  infiniteScrollViewElementNotFound = 'ZOOMRC/INFINITE_SCROLL_VIEW/ELEMENTS_NOT_FOUND',
  infiniteScrollViewScrollableTargetNotFound = 'ZOOMRC/INFINITE_SCROLL_VIEW/SCROLLABLE_TARGET_NOT_FOUND',

  imageEditorNotFoundCropperRef = 'ZOOMRC/IMAGE_EDITOR/CROPPER_REF_NOT_FOUND',
  imageEditorNotFoundCanvasElement = 'ZOOMRC/IMAGE_EDITOR/CANVAS_ELEMENT_NOT_FOUND',

  uploaderNotFoundFileInputRef = 'ZOOMRC/UPLOADER/FILE_INPUT_REF_NOT_FOUND',

  resizableMakerComputedStylesNotFound = 'ZOOMRC/RESIZABLE_MAKER/COMPUTED_STYLES_NOT_FOUND',
  resizableMakerResizableInfoRefNotFound = 'ZOOMRC/RESIZABLE_MAKER/RESIZABLE_INFO_REF_NOT_FOUND',

  richTextEditorEditorContainerRefNotFound = 'ZOOMRC/RICH_TEXT_EDITOR/EDITOR_CONTAINER_REF_NOT_FOUND',
  richTextEditorEditorScrollViewNotFound = 'ZOOMRC/RICH_TEXT_EDITOR/EDITOR_SCROLL_VIEW_NOT_FOUND',

  richTextEditorMakerEditorRefNotFound = 'ZOOMRC/RICH_TEXT_EDITOR_MAKER/EDITOR_REF_NOT_FOUND',
  richTextEditorMakerEditorRefIsFunction = 'ZOOMRC/RICH_TEXT_EDITOR_MAKER/EDITOR_REF_IS_FUNCTION',

  tableContainerRefNotFound = 'ZOOMRC/TABLE/CONTAINER_REF_NOT_FOUND',

  tableGeneratorTableRefNotFound = 'ZOOMRC/TABLE_GENERATOR/TABLE_REF_NOT_FOUND',

  tableTableElementTableRefNotFound = 'ZOOMRC/TABLE_TABLE_ELEMENT_TABLE_REF_NOT_FOUND',

  avatarEditorContainerRefNotFound = 'ZOOMRC/AVATAR_EDITOR/CONTAINER_REF_NOT_FOUND',
}
